apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-volume
spec:
  storageClassName: "es-cifs"
  accessModes: 
  - ReadWriteOnce 
  - ReadWriteMany 
  capacity:
    storage: 1Gi
  flexVolume:
    driver: juliohm/cifs
    options:
      opts: noperm
      server: 10.113.131.98
      share: /SMBShare      
    secretRef:
      name: smb-share-secret