apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: efk-ingress
  namespace: efk
spec:
  rules:
  - host: kibana.dmp
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: http    