apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: efk
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.3.0
        env:
        - name: CLUSTER_NAME
          value: myesdb
        #- name: SERVER_BASEPATH
        #  value: /api/v1/namespaces/default/services/kibana:http/proxy
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch-ingest:9200
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: http
