apiVersion: v1
kind: Pod
metadata:
  name: test-container
spec:
  containers:
  - name: test-host
    image: centos:latest
    command: ["sleep"]
    args: ["10000"]
    volumeMounts:
    - name: test-nfsvolume
      mountPath: /smbdata
  volumes:
  - name: test-nfsvolume
    persistentVolumeClaim:
      claimName: testpvc
        
