apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: juliohm-cifs-volumedriver-installer
spec:
  template:
    metadata:
      name: juliohm-cifs-volumedriver-installer
      labels:
        app: juliohm-cifs-volumedriver-installer
    spec:
      containers:
        - image: juliohm/kubernetes-cifs-volumedriver-installer:0.3
          name: flex-deploy
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-mount
      volumes:
        - name: flexvolume-mount
          hostPath:
            path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
